steps:
  - name: "cypress/base:10"
    id: "install-deps"
    entrypoint: "sh"
    args:
      - -c
      - |
        npm ci

  - name: "cypress/base:10"
    id: "build"
    waitFor: ["install-deps"]
    entrypoint: "sh"
    args:
      - -c
      - |
        npm run build

  - name: "gcr.io/cloud-builders/gsutil"
    id: "deploy"
    entrypoint: "sh"
    args:
      - -c
      - |
        if [ $BRANCH_NAME = master ]; then
          sh deploy.sh
        fi;

timeout: "600s"
