module.exports = {
  'include': ['src/**/*.js'],
  'exclude': ['src/main.js', 'src/router.js'],
  'reporter': ['html', 'text'],
  'require': ['@babel/register'],
  'instrument': false,
  'source-map': false,
  'clean': true,
  'cache': true,
  'eager': true,
  'check-coverage': true,
  'all': true,
  'per-file': true,
  'report-dir': 'coverage',
  'lines': 85,
  'statements': 85,
  'functions': 85,
  'branches': 85,
};
